#!/usr/bin/env sh
# Initialize Container Filesystem

set -e

# resolve app root
DIRECTORY_PREFIX=$(dirname $(readlink --canonicalize $(dirname $0)))

# fetch shims
mkdir --parent filesystem/usr/local/bin && \
curl --silent --show-error --location --output $DIRECTORY_PREFIX/filesystem/usr/local/bin/tree \
  --url https://raw.githubusercontent.com/ashenm/environment/master/linux/components/bin/tree

# environment.sh
curl --silent --show-error --location --output $DIRECTORY_PREFIX/filesystem/etc/profile.d/environment.sh \
  --url https://raw.githubusercontent.com/ashenm/environment/master/linux/components/etc/profile.d/environment.sh

# fetch eslint conffile
curl --silent --show-error --location --output $DIRECTORY_PREFIX/filesystem/etc/skel/.eslintrc.json \
  --url https://gist.githubusercontent.com/ashenm/537a91f9c864d6ef6180790d9076047d/raw/eslintrc.json

# clinch permissions
find $DIRECTORY_PREFIX/filesystem -type d -exec chmod 755 {} \;
find $DIRECTORY_PREFIX/filesystem/etc -type f -exec chmod 644 {} \;
find $DIRECTORY_PREFIX/filesystem/etc/sudoers.d -type d -exec chmod 750 {} \;
find $DIRECTORY_PREFIX/filesystem/etc/sudoers.d -type f -exec chmod 440 {} \;
find $DIRECTORY_PREFIX/filesystem/etc/skel -mindepth 1 -type d -exec chmod 700 {} \;
find $DIRECTORY_PREFIX/filesystem/etc/skel -mindepth 1 -type f -exec chmod 600 {} \;
find $DIRECTORY_PREFIX/filesystem/usr/local/sbin -type f -exec chmod 755 {} \;
find $DIRECTORY_PREFIX/filesystem/usr/local/bin -type f -exec chmod 755 {} \;
find $DIRECTORY_PREFIX/filesystem/usr/local/share -type f -exec chmod 664 {} \;

# extend ssh_config
tee --append $DIRECTORY_PREFIX/filesystem/etc/ssh/workspace <<EOF

# Avoid read-only user host
# key database write failure
Host *
    UserKnownHostsFile /opt/ssh/known_hosts
EOF
