actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/*"

latest:
  - changed-files:
      - any-glob-to-any-file:
          - "src/latest/*"

railsbank:
  - changed-files:
      - any-glob-to-any-file:
          - "src/railsbank/*"

secure-agility:
  - changed-files:
      - any-glob-to-any-file:
          - "src/secure-agility/*"

singlife:
  - changed-files:
      - any-glob-to-any-file:
          - "src/singlife/*"

stanford-cs143:
  - changed-files:
      - any-glob-to-any-file:
          - "src/stanford-cs143/*"
