#!/usr/bin/env sh

set -e

# fetch all repo related image references
DOCKER_FLAVORS=`docker images --filter=reference="${GITHUB_REPOSITORY}" --format "{{.Tag}}"`

# abbreviate commit hash
COMMIT_SHA=`expr substr ${GITHUB_SHA} 1 7`

# use github image registry
DOCKER_REPOSITORY="docker.pkg.github.com"

# push commit hash tags
echo "${DOCKER_FLAVORS}" | xargs -I"{}" docker tag ${GITHUB_REPOSITORY}:{} ${DOCKER_REPOSITORY}/${GITHUB_REPOSITORY}:{}-${COMMIT_SHA}
echo "${DOCKER_FLAVORS}" | parallel --progress docker push ${DOCKER_REPOSITORY}/${GITHUB_REPOSITORY}:{}-${COMMIT_SHA}
