#!/usr/bin/env sh

set -e

# image tar dir
TEMPORARY_DIRECTORY=${RUNNER_TEMP:-/tmp}
ARTEFACTS_DIRECTORY=${ARTEFACTS_DIRECTORY:-$TEMPORARY_DIRECTORY/images}

# list artefacts
ls -al $ARTEFACTS_DIRECTORY

# load images
find $ARTEFACTS_DIRECTORY -mindepth 1 -maxdepth 1 -type f -iname '*.tar'
find $ARTEFACTS_DIRECTORY -mindepth 1 -maxdepth 1 -type f -iname '*.tar' | parallel --progress docker load --input {}

# list images
docker images --all
