sudo:
  required

language:
  generic

services:
  docker

install:
  - git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - find etc -type d -exec chmod 755 {} \;
  - find etc -type f -exec chmod 644 {} \;

script:
  - docker build -t "$TRAVIS_REPO_SLUG" .
  - ~/official-images/test/run.sh -c ~/official-images/test/config.sh -c ./tests/config.sh "$TRAVIS_REPO_SLUG"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push "$TRAVIS_REPO_SLUG"
