#!/usr/bin/env sh
# Trigger Dependent Builds

set -e

# avoid reverse dependecy
# triggers on CI/CD cron jobs
test "$TRAVIS_EVENT_TYPE" = "cron" && \
  exit

# truncate commit hash
TRAVIS_COMMIT=`expr substr "$TRAVIS_COMMIT" 1 7`

# ashenm/environment
if [ -n "$(git diff --name-only HEAD~1 HEAD | egrep '^(:?scripts/workspace|filesystem/etc/.*)$')" ]; then

  curl --fail --silent --show-error --request POST --output /dev/null \
    --header "Content-Type: application/json" --header "Accept: application/json" \
    --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_PRO_API_TOKEN" \
    --data "{ \"request\": { \"branch\": \"master\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
    --url "https://api.travis-ci.com/repo/ashenm%2Fenvironment/requests"

fi

# ashenm/workspace:stanford-cs143
curl --fail --silent --show-error --request POST --output /dev/null \
  --header "Content-Type: application/json" --header "Accept: application/json" \
  --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_API_TOKEN" \
  --data "{ \"request\": { \"branch\": \"stanford-cs143\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
  --url "https://api.travis-ci.org/repo/ashenm%2Fworkspace/requests"

# ashenm/xworkspace
curl --fail --silent --show-error --request POST --output /dev/null \
  --header "Content-Type: application/json" --header "Accept: application/json" \
  --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_API_TOKEN" \
  --data "{ \"request\": { \"branch\": \"latest\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
  --url "https://api.travis-ci.org/repo/ashenm%2Fxworkspace/requests"

# ashenm/shell
curl --fail --silent --show-error --request POST --output /dev/null \
  --header "Content-Type: application/json" --header "Accept: application/json" \
  --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_PRO_API_TOKEN" \
  --data "{ \"request\": { \"branch\": \"latest\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
  --url "https://api.travis-ci.com/repo/ashenm%2Fshell/requests"
