#!/usr/bin/env sh
# Trigger Dependent Builds

set -e

# truncate commit hash
TRAVIS_COMMIT=`expr substr "$TRAVIS_COMMIT" 1 7`

# ashenm/environment
if [ -n "$(git diff --name-only HEAD~1 HEAD | egrep --file $(dirname $0)/culminate.patterns)" \
 -a "${TRAVIS_COMMIT_MESSAGE}" = "${TRAVIS_COMMIT_MESSAGE##* ashenm/environment}" ]; then

  curl --fail --silent --show-error --request POST --output /dev/null \
    --header "Content-Type: application/json" --header "Accept: application/json" \
    --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_API_TOKEN" \
    --data "{ \"request\": { \"branch\": \"master\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
    --url "https://api.travis-ci.com/repo/ashenm%2Fenvironment/requests"

fi

# ashenm/ide
curl --fail --silent --show-error --request POST --output /dev/null \
  --header "Content-Type: application/json" --header "Accept: application/json" \
  --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_API_TOKEN" \
  --data "{ \"request\": { \"branch\": \"latest\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
  --url "https://api.travis-ci.com/repo/ashenm%2Fide/requests"

# ashenm/workspace:railsbank
# curl --fail --silent --show-error --request POST --output /dev/null \
#   --header "Content-Type: application/json" --header "Accept: application/json" \
#   --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_API_TOKEN" \
#   --data "{ \"request\": { \"branch\": \"railsbank\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
#   --url "https://api.travis-ci.com/repo/ashenm%2Fworkspace/requests"

# ashenm/workspace:stanford-cs143
# curl --fail --silent --show-error --request POST --output /dev/null \
#   --header "Content-Type: application/json" --header "Accept: application/json" \
#   --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_API_TOKEN" \
#   --data "{ \"request\": { \"branch\": \"stanford-cs143\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
#   --url "https://api.travis-ci.com/repo/ashenm%2Fworkspace/requests"

# ashenm/shell
curl --fail --silent --show-error --request POST --output /dev/null \
  --header "Content-Type: application/json" --header "Accept: application/json" \
  --header "Travis-API-Version: 3" --header "Authorization: token $TRAVIS_API_TOKEN" \
  --data "{ \"request\": { \"branch\": \"latest\", \"message\": \"Build to parity with commit "$TRAVIS_COMMIT" on "$TRAVIS_REPO_SLUG"\" } }" \
  --url "https://api.travis-ci.com/repo/ashenm%2Fshell/requests"
