name: Build Image

on:
  - push
  - pull_request

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: make install
      - run: make build
      - run: make assess
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login --password-stdin --username ashenm docker.pkg.github.com
          docker tag ashenm/workspace:latest-alpha docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}:${GITHUB_SHA:0:7}
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}:${GITHUB_SHA:0:7}
      - if: github.event_name == 'push' && github.ref == 'refs/heads/latest'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login --password-stdin --username ashenm docker.pkg.github.com
          docker tag ashenm/workspace:latest-alpha docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}:latest
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}:latest
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[Skip CI]') }}

# vim: set expandtab shiftwidth=2 syntax=yaml:
