name: Build Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - master

jobs:
  metadata:
    steps:
      - id: git
        run: echo "build_commit_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
    outputs:
      build_commit_sha: ${{ steps.git.outputs.build_commit_sha }}
    runs-on: ubuntu-latest

  latest:
    needs:
      - metadata
    if: ${{ !startsWith(github.event.head_commit.message, '[Skip CI]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: src/latest
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ github.job }}:${{ needs.metadata.outputs.build_commit_sha }}
      - if: ${{ github.ref_name == 'master' }}
        run: |
          echo ${DOCKER_PASSWORD} | docker login --password-stdin --username ${DOCKER_USERNAME}
          docker buildx imagetools create --tag ${{ github.repository }}:${{ github.job }} \
            ghcr.io/${{ github.repository }}/${{ github.job }}/${{ needs.metadata.outputs.build_commit_sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-22.04

  railsbank:
    needs:
      - latest
      - metadata
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
        docker pull ghcr.io/${{ github.repository }}/latest:${{ needs.metadata.outputs.build_commit_sha }}
        docker tag ghcr.io/${{ github.repository }}/latest:${{ needs.metadata.outputs.build_commit_sha }} ${{ github.repository }}:latest
      - uses: docker/build-push-action@v4
        with:
          context: src/railsbank
          platforms: linux/amd64,linux/arm64
          pull: false
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ github.job }}:${{ needs.metadata.outputs.build_commit_sha }}
      - if: ${{ github.ref_name == 'master' }}
        run: |
          echo ${DOCKER_PASSWORD} | docker login --password-stdin --username ${DOCKER_USERNAME}
          docker buildx imagetools create --tag ${{ github.repository }}:${{ github.job }} \
            ghcr.io/${{ github.repository }}/${{ github.job }}/${{ needs.metadata.outputs.build_commit_sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-22.04

  stanford-cs143:
    needs:
      - latest
      - metadata
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run:  |
        docker pull ghcr.io/${{ github.repository }}/latest:${{ needs.metadata.outputs.build_commit_sha }}
        docker tag ghcr.io/${{ github.repository }}/latest:${{ needs.metadata.outputs.build_commit_sha }} ${{ github.repository }}:latest
      - uses: docker/build-push-action@v4
        with:
          context: src/railsbank
          platforms: linux/amd64,linux/arm64
          pull: false
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ github.job }}-cs143:${{ needs.metadata.outputs.build_commit_sha }}
      - if: ${{ github.ref_name == 'master' }}
        run: |
          echo ${DOCKER_PASSWORD} | docker login --password-stdin --username ${DOCKER_USERNAME}
          docker buildx imagetools create --tag ${{ github.repository }}:${{ github.job }} \
            ghcr.io/${{ github.repository }}/${{ github.job }}/${{ needs.metadata.outputs.build_commit_sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-22.04

  # slack:
  #   needs:
  #     - build
  #     - assess
  #     - github
  #     - dockerhub
  #   if: ${{ always() }}
  #   steps:
  #     - uses: Gamesight/slack-workflow-status@master
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         channel: '#github'
  #         name: 'GitHub Workflow'
  #   runs-on: ubuntu-22.04

# vim: set expandtab shiftwidth=2 syntax=yaml:
