name: Deployment Cleanup

on:
  delete:
    branches:
      - '**'
  push:
    branches:
      - latest

jobs:
  dockerhub:
    if: ${{ github.event_name == 'delete' }}
    name: Docker Hub
    steps:
      - uses: ashenm/docker-hub-cleanup@latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          repository: ashenm/workspace
          github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
  github:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: GitHub Packages
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'workspace'
    runs-on: ubuntu-latest

# vim: set expandtab shiftwidth=2 syntax=yaml:
