name: (resuable) Build

on:
  workflow_call:
    inputs:
      build-args:
        type: string
        required: false
      platform:
        type: string
        required: true
      source:
        type: string
        required: true

jobs:
  build-image:
    steps:
      - run: |
          DOCKER_IMAGE_TARGET_PLATFORM=${{ inputs.platform }}
          echo "DOCKER_IMAGE_TARGET_PLATFORM=${DOCKER_IMAGE_TARGET_PLATFORM//\//-}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ inputs.platform }}
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ./src/${{ inputs.source }}/scripts/init-filesystem
      - id: build
        uses: docker/build-push-action@v5
        with:
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha,scope=buildkit-${{ inputs.source }}-${{ inputs.platform }}
          cache-to: type=gha,mode=max,scope=buildkit-${{ inputs.source }}-${{ inputs.platform }}
          context: src/${{ inputs.source }}
          platforms: ${{ inputs.platform }}
          pull: true
          push: true
          outputs: type=image,name=ghcr.io/${{ github.repository }}/${{ inputs.source }},name-canonical=true,push-by-digest=true,push=true
      - run: |
          mkdir --parent /tmp/digests
          DOCKER_IMAGE_DIGEST=${{ steps.build.outputs.digest }}
          touch /tmp/digests/${DOCKER_IMAGE_DIGEST#sha256:}
      - uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.source }}-${{ env.DOCKER_IMAGE_TARGET_PLATFORM }}
          path: /tmp/digests/*
          if-no-files-found: error
    runs-on: ubuntu-22.04
