name: Scan Image

on:
  workflow_run:
    branches:
      - master
      - "workflows/*"
    workflows:
      - Build Image
    types:
      - completed

jobs:
  metadata:
    steps:
      - id: digests
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id,
            });
            const digests = artifacts.data.artifacts.filter(artifact => artifact.name.startsWith('digest-'));
            return JSON.stringify(digests.map(digest => digest.name));
          result-encoding: json
      - run: echo "${{ steps.digests.outputs.result }}"
    runs-on: ubuntu-latest
